# Generated by Django 4.2.1 on 2023-07-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_who_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='who_liked',
        ),
    ]
